const players = [
  {
    id: 1,
    nome: "Thibaut Courtois",
    numero: 1,
    posicao: "G",
    idade: 32,
    altura: "2.01 m",
    peso: "96 kg",
    nacionalidade: "Bélgica",
  },
  {
    id: 2,
    nome: "Andriy Lunin",
    numero: 13,
    posicao: "G",
    idade: 25,
    altura: "1.91 m",
    peso: "78 kg",
    nacionalidade: "Ucrânia",
  },
  {
    id: 3,
    nome: "Rodrygo",
    numero: 21,
    posicao: "A",
    idade: 23,
    altura: "1.74 m",
    peso: "68 kg",
    nacionalidade: "Brasil",
  },
  {
    id: 4,
    nome: "Vinícius Júnior",
    numero: 11,
    posicao: "A",
    idade: 23,
    altura: "1.76 m",
    peso: "73 kg",
    nacionalidade: "Brasil",
  },
  {
    id: 5,
    nome: "Endrick",
    numero: "",
    posicao: "A",
    idade: 18,
    altura: "1.75 m",
    peso: "68 kg",
    nacionalidade: "Brasil",
  },
  {
    id: 6,
    nome: "Dani Carvajal",
    numero: 2,
    posicao: "D",
    idade: 32,
    altura: "1.73 m",
    peso: "73 kg",
    nacionalidade: "Espanha",
  },
  {
    id: 7,
    nome: "Éder Militão",
    numero: 3,
    posicao: "D",
    idade: 26,
    altura: "1.85 m",
    peso: "78 kg",
    nacionalidade: "Brasil",
  },
  {
    id: 8,
    nome: "David Alaba",
    numero: 4,
    posicao: "D",
    idade: 32,
    altura: "1.80 m",
    peso: "78 kg",
    nacionalidade: "Áustria",
  },
  {
    id: 9,
    nome: "Arda Güler",
    numero: 15,
    posicao: "M",
    idade: 19,
    altura: "1.75 m",
    peso: "67 kg",
    nacionalidade: "Turquia",
  },
  {
    id: 10,
    nome: "Jesús Vallejo",
    numero: 18,
    posicao: "D",
    idade: 27,
    altura: "1.83 m",
    peso: "78 kg",
    nacionalidade: "Espanha",
  },
  {
    id: 11,
    nome: "Fran García",
    numero: 20,
    posicao: "D",
    idade: 24,
    altura: "1.68 m",
    peso: "68 kg",
    nacionalidade: "Espanha",
  },
  {
    id: 12,
    nome: "Antonio Rüdiger",
    numero: 22,
    posicao: "D",
    idade: 31,
    altura: "1.91 m",
    peso: "83 kg",
    nacionalidade: "Alemanha",
  },
  {
    id: 13,
    nome: "Ferland Mendy",
    numero: 23,
    posicao: "D",
    idade: 29,
    altura: "1.80 m",
    peso: "73 kg",
    nacionalidade: "França",
  },
  {
    id: 14,
    nome: "Lucas Vázquez",
    numero: 17,
    posicao: "M",
    idade: 33,
    altura: "1.73 m",
    peso: "71 kg",
    nacionalidade: "Espanha",
  },
  {
    id: 15,
    nome: "Aurélien Tchouaméni",
    numero: 14,
    posicao: "M",
    idade: 24,
    altura: "1.88 m",
    peso: "81 kg",
    nacionalidade: "França",
  },
  {
    id: 16,
    nome: "Luka Modric",
    numero: 10,
    posicao: "M",
    idade: 38,
    altura: "1.73 m",
    peso: "66 kg",
    nacionalidade: "Croácia",
  },
  {
    id: 17,
    nome: "Federico Valverde",
    numero: 8,
    posicao: "M",
    idade: 26,
    altura: "1.83 m",
    peso: "78 kg",
    nacionalidade: "Uruguai",
  },
  {
    id: 18,
    nome: "Jude Bellingham",
    numero: 5,
    posicao: "M",
    idade: 21,
    altura: "1.85 m",
    peso: "73 kg",
    nacionalidade: "Inglaterra",
  },
  {
    id: 19,
    nome: "Reiner",
    numero: "",
    posicao: "M",
    idade: 22,
    altura: "1.85 m",
    peso: "78 kg",
    nacionalidade: "Brasil",
  },
];

export { players };
